name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_docker_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push back-end images on DockerHub and AWS ECR
        working-directory: clear-money-src/api
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:latest
  
      - name: Build and push front-end images on DockerHub and AWS ECR
        working-directory: clear-money-src/client
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest