name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: clear-money-src/api
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nest-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nest-app:latest
