name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_docker_images:
    
    runs-on: ubuntu-latest

    steps:
      # configuration

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
      
          
      # build and push images
    
        # DockerHub

      - name: Build and push back-end images on DockerHub
        working-directory: clear-money-src/api
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:latest
  
      - name: Build and push front-end images on DockerHub and AWS ECR
        working-directory: clear-money-src/client
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest
        
        # Amazon ECR
        
      - name: Build, tag, and push backend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: backend
        working-directory: clear-money-src/api
        run: |
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push front-end image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY: client
        working-directory: clear-money-src/client
        run: |
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG            