name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test_and_deploy_docker_images:
        runs-on: ubuntu-latest

        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          FirebaseApiKey: ${{ secrets.FirebaseApiKey }}
          FirebaseAuthDomain: ${{ secrets.FirebaseAuthDomain }}
          FirebaseProjectId: ${{ secrets.FirebaseProjectId }}
          FirebaseStorageBucket: ${{ secrets.FirebaseStorageBucket }}
          FirebaseMessagingSenderId: ${{ secrets.FirebaseMessagingSenderId }}
          FirebaseAppId: ${{ secrets.FirebaseAppId }}
          FIREBASE_TYPE: ${{ secrets.FIREBASE_TYPE }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
          FIREBASE_TOKEN_URI: ${{ secrets.FIREBASE_TOKEN_URI }}
          FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
          FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
          FIREBASE_UNIVERSE_DOMAIN: ${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}
          
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20.8.0

            - name: Install Dependencies and Run Tests
              working-directory: clear-money-src/api
              run: |
                npm install
                npm run test